insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR020-HT','020');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR020CUPB-HT','020CUPB');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR021-HT','021');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR022-HT','022');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR052-STICKER','052');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR053-STICKER','053');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR151-HT','151');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR152-HT','152');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR210-LB','210');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR212-LB','212');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR213-LB','213');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR214-LB','214');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR303-HANGER','303');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR304-HANGER','304');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR305-HANGER','305');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR306-HANGER','306');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR311-JER-HT','311');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR312-SKR-HT','312');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR313-BOR-HT','313');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR314-STR-HT','314');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR315-BOYL-HT','315');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR316-FLR-HT','316');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR317-ANR-HT','317');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR318-HAR-HT','318');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR320-HT','320');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR321-JE-JT-32','321');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR321-JE-JT-34','321');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR321-JE-JT-36','321');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR321-JE-JT-38','321');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR321-JE-JT-40','321');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR321-JE-JT-42','321');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR321-JE-JT-44','321');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR322-SK-JT-32','322');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR322-SK-JT-34','322');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR322-SK-JT-36','322');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR322-SK-JT-38','322');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR322-SK-JT-40','322');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR322-SK-JT-42','322');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR322-SK-JT-44','322');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR323-BOO-JT-32','323');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR323-BOO-JT-34','323');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR323-BOO-JT-36','323');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR323-BOO-JT-38','323');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR323-BOO-JT-40','323');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR323-BOO-JT-42','323');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR323-BOO-JT-44','323');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR324-ST-JT-32','324');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR324-ST-JT-34','324');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR324-ST-JT-36','324');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR324-ST-JT-38','324');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR324-ST-JT-40','324');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR324-ST-JT-42','324');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR324-ST-JT-44','324');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR325-BOY-JT-32','325');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR325-BOY-JT-34','325');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR325-BOY-JT-36','325');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR325-BOY-JT-38','325');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR325-BOY-JT-40','325');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR325-BOY-JT-42','325');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR325-BOY-JT-44','325');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR326-FL-JT-32','326');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR326-FL-JT-34','326');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR326-FL-JT-36','326');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR326-FL-JT-38','326');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR326-FL-JT-40','326');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR326-FL-JT-42','326');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR326-FL-JT-44','326');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR327-AN-JT-32','327');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR327-AN-JT-34','327');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR327-AN-JT-36','327');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR327-AN-JT-38','327');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR327-AN-JT-40','327');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR327-AN-JT-42','327');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR327-AN-JT-44','327');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR328-HA-JT-32','328');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR328-HA-JT-34','328');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR328-HA-JT-36','328');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR328-HA-JT-38','328');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR328-HA-JT-40','328');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR328-HA-JT-42','328');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR328-HA-JT-44','328');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR329-SH-JT-32','329');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR329-SH-JT-34','329');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR329-SH-JT-36','329');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR329-SH-JT-38','329');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR329-SH-JT-40','329');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR329-SH-JT-42','329');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR330-BE-JT-32','330');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR330-BE-JT-34','330');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR330-BE-JT-36','330');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR330-BE-JT-38','330');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR330-BE-JT-40','330');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR330-BE-JT-42','330');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR331-CA-LB','331');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR332-EM-LB','332');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR333-SO-LB','333');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR334-CO-LB','334');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR341-SKL-HT','341');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR342-BOL-HT','342');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR343-BOH-HT','343');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR344-STL-HT','344');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR345-FLH-HT','345');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR346-SHR-HT','346');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR347-BER-HT','347');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR351-JE-JT-32','351');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR351-JE-JT-34','351');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR351-JE-JT-36','351');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR351-JE-JT-38','351');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR351-JE-JT-40','351');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR351-JE-JT-42','351');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR351-JE-JT-44','351');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR352-SK-JT-32','352');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR352-SK-JT-34','352');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR352-SK-JT-36','352');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR352-SK-JT-38','352');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR352-SK-JT-40','352');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR352-SK-JT-42','352');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR352-SK-JT-44','352');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR353-BOO-JT-32','353');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR353-BOO-JT-34','353');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR353-BOO-JT-36','353');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR353-BOO-JT-38','353');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR353-BOO-JT-40','353');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR353-BOO-JT-42','353');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR353-BOO-JT-44','353');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR354-ST-JT-32','354');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR354-ST-JT-34','354');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR354-ST-JT-36','354');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR354-ST-JT-38','354');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR354-ST-JT-40','354');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR354-ST-JT-42','354');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR354-ST-JT-44','354');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR355-BOY-JT-32','355');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR355-BOY-JT-34','355');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR355-BOY-JT-36','355');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR355-BOY-JT-38','355');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR355-BOY-JT-40','355');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR355-BOY-JT-42','355');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR355-BOY-JT-44','355');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR356-FL-JT-32','356');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR356-FL-JT-34','356');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR356-FL-JT-36','356');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR356-FL-JT-38','356');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR356-FL-JT-40','356');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR356-FL-JT-42','356');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR356-FL-JT-44','356');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR357-HT','357');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR357R2-HT','357');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('OR358-HT','358');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('ORCL-#1','ORCL-#1');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('ORCL-#2','ORCL-#2');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('ORCL-#3','ORCL-#3');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('ORCL-#4','ORCL-#4');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('ORDOWN-HT','253');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('ORSAY HAND MADE HANGTAGS','335');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('ORSAY HANGER (FOR FLIP FLOP)','ORSAY HANGER (FOR FLIP FLOP)');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('ORSAY KNITWEAR LABEL BLACK','ORSAY KNITWEAR LABEL BLACK');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('ORSAY KNITWEAR LABEL MILK','ORSAY KNITWEAR LABEL MILK');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('ORSML204-CF','204');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('ORWOOL-HT','254');
insert into mglobal_master_item (erp_item_code, mg_item_code) values ('ORWRE-HT','ORWRE-HT');


insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (1,'ORSAY','ORSAY','ORSAY');
insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (2,'PIMKIE','PIMKIE','PIMKIE');
insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (4,'SOA','STATE OF ART','STATE OF ART');
insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (5,'PTT','PRINCESS TAM TAM','PRINCESS TAM TAM');
insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (52,'Orchestra','ORCHESTRA KAZIBAO','ORCHESTRA');
insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (206,'MOHITO','MOHITO','MOHITO');
insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (228,'Scottage','SCOTTAGE','SCOTTAGE');
insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (257,'DIM','DB APPAREL','DIM');
insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (276,'Vaude','VAUDE','VAUDE');
insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (383,'Hallhuber','HALLHUBER','HALLHUBER');
insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (422,'Sans Branded Apparel S.L.','DB APPAREL','ABANDERADO - BOYS');
insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (422,'Sans Branded Apparel S.L.','DB APPAREL','ABANDERADO - MENS');
insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (437,'Jacqueline Riu','JACQUELINE RIU','JACQUELINE RIU');
insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (445,'HOUSE','HOUSE','BASIC');
insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (445,'HOUSE','HOUSE','LADIES');
insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (445,'HOUSE','HOUSE','MENS');
insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (446,'Peek and Cloppenburg','PEEK AND CLOPPENBURG','CHRISTIAN BERG');
insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (446,'Peek and Cloppenburg','PEEK AND CLOPPENBURG','PEEK AND CLOPPENBURG');
insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (458,'Pierre Cardin','PIERRE CARDIN','PIERRE CARDIN');
insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (464,'InterArt of Cashmere World AG','FTC','FTC');
insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (480,'Kempa','UHLSPORT GMBH','KEMPA');
insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (480,'Kempa','UHLSPORT GMBH','SPALDING');
insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (480,'Kempa','UHLSPORT GMBH','UHLSPORT');
insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (484,'Magic Body Fashion','MAGIC BODY FASHION','MAGIC BODY FASHION');
insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (485,'EDELRID GmbH & Co. KG','EDELRID GMBH','EDELRID');
insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (488,'4F','OTCF SP. Z.O.O.','4F');
insert into mglobal_master_client (client_id, client_name, erp_program, erp_brand) values (489,'FOB','OTCF SP. Z.O.O.','FOB');
