INSERT INTO "orchestra_customer" ("id", "name", "contact", "email", "team") VALUES (1, 'POLYWELL TEXTILES (INTERNATIONAL) CO., LTD', 'MS MANDY/ MS KELLY', 'Mandy@polywell-inc.com; kelly@polywell-inc.com', 'HK');
INSERT INTO "orchestra_customer" ("id", "name", "contact", "email", "team") VALUES (2, 'WLLSUM TRADING CO. LTD', 'MR KENNETH / MS GIGI', 'kenneth@wellsum.com; gigi@wellsum.com', 'HK');
INSERT INTO "orchestra_customer" ("id", "name", "contact", "email", "team") VALUES (3, 'SHENZHEN WINSOME ENTERPRISE CO., LTD.', 'MR TINY ZHANG / MS SI TU HUI XIA', 'tinyzhang80@126.com; situhuixia@163.com', 'HK');
INSERT INTO "orchestra_customer" ("id", "name", "contact", "email", "team") VALUES (4, 'MARKET PLUS (INT’L) LTD', 'MR BILL CHAU / MR DICKY', 'bill@markplus.com.hk; dicky@markplus.com.hk', 'HK');
INSERT INTO "orchestra_customer" ("id", "name", "contact", "email", "team") VALUES (5, 'LEI SAO LAI COMPANY', 'MS ESTHER LEI / MR JOSEPH CHAN', 'esther@henoch.com.cn; joseph@henoch.com.cn', 'HK');
INSERT INTO "orchestra_customer" ("id", "name", "contact", "email", "team") VALUES (6, 'SHING FUN INTERNATIONAL INDUSTRIAL LTD.', 'MR ERIC YOUNG', 'ericyoung@shingfun.com', 'HK');
INSERT INTO "orchestra_customer" ("id", "name", "contact", "email", "team") VALUES (7, 'SKYLANE CORPORATION LTD', 'MS SCARLET MAN / MS TAMMY WONG', 'skylane@netvigator.com', 'HK');
INSERT INTO "orchestra_customer" ("id", "name", "contact", "email", "team") VALUES (8, 'WING FAI COMPANY', 'MR ANDY WONG', 'andywwf@netvigator.com', 'HK');
INSERT INTO "orchestra_customer" ("id", "name", "contact", "email", "team") VALUES (9, 'Mantex Enterprises (HK) LTD', 'MS SHIRLEY / MR LIU JUN', 'shirley@mantexcn.com; liu@mantexcn.com', 'HK');
INSERT INTO "orchestra_customer" ("id", "name", "contact", "email", "team") VALUES (10, 'YUEN FUNG GARMENT MFG. CO., LTD.', 'MS MABLE / MS QUEENIE', 'mabel@yuenfunggmt.com.hk; queenie@yuenfunggmt.com.hk', 'HK');

INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (1, 'T-SHIRT', 'TEE SHIRT', 'تي شيرت', 'original', '00', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (2, 'DEBARDEUR', 'TANK-TOP', 'تي شيرت بدون أكمام', 'original', '01', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (3, 'TOP', 'TOP', 'قميص توب', 'original', '01', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (4, 'POLO', 'POLO', 'قميص بولو', 'original', '02', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (5, 'CHEMISE', 'SHIRT', 'قميص', 'original', '03', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (6, 'CHEMISIER', 'GIRL SHIRT', 'قميص بنت', 'original', '04', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (7, 'SOUS PULL', 'SOUS PULL', 'سترة تحتية', 'original', '06', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (8, 'SWEAT', 'SWEAT SHIRT', 'قميص ضد العرق', 'original', '07', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (9, 'GILET', 'CARDIGAN', 'صداري', 'original', '08', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (10, 'PULL', 'PULLOVER', 'سترة صوفية', 'original', '10', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (11, 'SALOPETTE LONGUE', 'LONG OVERALL', 'وزرة طويلة', 'original', '11', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (12, 'SALOPETTE COURTE', 'SHORT OVERALL', 'وزرة قصيرة', 'original', '11', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (13, 'PANTALON', 'PANTS', 'سروال', 'original', '12', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (14, 'JEANS', 'JEANS', 'جينز', 'original', '13', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (15, 'PANTALON DE JOGGING', 'JOGGING PANTS', 'سروال ركض', 'original', '14', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (16, 'CALECON', 'LEGGINGS', 'سروال تحتي', 'original', '15', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (17, 'PANTALON DE SKI', 'SKY PANTS', 'سروال التزلج', 'original', '16', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (18, 'CORSAIRE PANTACOURT', 'CAPRI', 'سروال قصير', 'original', '17', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (19, 'TUNIQUE', 'TUNIC', 'سترة قصيرة', 'original', '18', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (20, 'BERMUDAS', 'BERMUDAS', 'برمودا', 'original', '19', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (21, 'SHORT BLOOMER', 'BLOOMER', 'سروال قصير', 'original', '20', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (22, 'JUPE LONGUE', 'LONG SKIRT', 'تنورة طويلة', 'original', '22', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (23, 'JUPE COURTE', 'SHORT SKIRT', 'تنورة قصيرة', 'original', '22', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (24, 'MAILLOT DE BAIN', 'SWIMWEAR', 'ثوب سباحة', 'original', '23', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (25, 'ROBE', 'DRESS', 'فستان', 'original', '24', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (26, 'COMBINAISON', 'COMBINAISON', 'مؤتلفة', 'original', '25', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (27, 'ENSEMBLE SILHOUETTE', 'SET', 'طقم الشكل', 'original', '28', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (28, 'JOGGING', 'JOGGING', 'طقم للركض', 'original', '29', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (29, 'LINGE DE LIT', 'BED SET', 'طقم للفراش', 'original', '30', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (30, 'BLOUSON SKI', 'SKY PARKA', 'سترة التزلج', 'original', '31', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (31, 'VESTE', 'JACKET', 'بالطو', 'original', '33', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (32, 'COUPE VENT', 'WINDBREAKER', 'بالطو مانع الرياح', 'original', '35', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (33, 'IMPERMEABLE', 'RAINCOAT', 'معطف ضد المطر', 'original', '36', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (34, 'Ensemble 2 en 1', 'SET 2 in 1', 'طقم 2 في 1', 'original', '37', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (35, 'PARKA', 'PARKA', 'سترة فرائية', 'original', '38', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (36, 'PILOTE', 'PILOT', 'ثوب طيار', 'original', '39', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (37, 'COMBINAISON SKI', 'SKY COMBINAISON', 'مؤتلفة التزلج', 'original', '40', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (38, 'PYJAMA', 'PYJAMA', 'منامة', 'original', '41', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (39, 'ROBE DE CHAMBRE', 'HOUSE COAT', 'لباس البيت', 'original', '42', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (40, 'PEIGNOIR', 'PEIGNOIR', 'رداء البيت', 'original', '43', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (41, 'DORS BIEN', 'DORS BIEN', 'منامة رضيع', 'original', '44', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (42, 'CARRE DE BAIN', 'TERRY TOWEL', 'الحمام مجموعة', 'original', '45', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (43, 'CHEMISE DE NUIT', 'NIGHT DRESS', 'ثوب النوم', 'original', '46', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (44, 'ENSEMBLE SOUS VETEMENTS', 'SET UNDERWEAR', 'طقم ملابس داخلية', 'original', '49', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (45, 'SLIP/BOXER/CULOTTE', 'BRIEF/BOXER', 'سروال تحتاني/بوكسر', 'original', '51', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (46, 'BODY', 'BODY', 'بودي', 'original', '53', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (47, 'MAILLOT 1 PIECE', 'SWIMWEAR 1 PIECE', 'ثوب سباحة قطعة واحدة', 'original', '58', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (48, 'MAILLOT 2 PIECES', 'SWIMWEAR 2 PIECES', 'ثوب سباحة قطعتين', 'original', '59', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (49, 'SLIP DE BAIN', 'SWIMWEAR', 'سروال سباحة', 'original', '60', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (50, 'SHORT DE BAIN', 'SWIMWEAR SHORT', 'شورت سباحة', 'original', '61', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (51, 'ENSEMBLE DE PLAGE', 'BEACH SET', 'طقم للبحر', 'original', '62', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (52, 'ENSEMBLE ROBE', 'DRESS SET', 'طقم للفستان', 'original', '63', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (53, 'ENSEMBLE SALOPETTE', 'OVERALL SET', 'طقم للوزرة', 'original', '64', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (54, 'ENSEMBLE SHORT', 'SHORT SET', 'طقم للشورت', 'original', '65', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (55, 'ENSEMBLE TUNIQUE', 'TUNIC SET', 'طقم للسترة للقصيرة', 'original', '66', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (56, 'DOUDOUNE', 'PARKA', 'معطف', 'original', '67', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (57, 'MANTEAU', 'COAT', 'معطف', 'original', '68', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (58, 'BLOUSON', 'JACKET', 'سترة', 'original', '69', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (59, 'SERVIETTE PLAGE', 'BEACH TOWEL', 'منشفة البحر', 'original', '70', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (60, 'COLLIER', 'NECKLACE', 'قلادة', 'original', '73', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (61, 'CHAPEAU', 'HAT', 'قبعة', 'original', '75', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (62, 'ECHARPE', 'SCARF', 'وشاح', 'original', '76', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (63, 'FOULARD', 'SCARF', 'منديل', 'original', '76', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (64, 'GANT', 'GLOVES', 'قفاز', 'original', '77', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (65, 'MOUFLE', 'MITTEN', 'قفاز', 'original', '77', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (66, 'PELUCHE', 'TOYS', 'لعبة وبر', 'original', '80', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (67, 'CHAUSSON', 'BOOTEE', 'شبشب', 'original', '81', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (68, 'CEINTURE', 'BELT', 'حزام', 'original', '82', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (69, 'BRETELLE', 'SHOULDER STRAP', 'حمالة الكتف', 'original', '82', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (70, 'CRAVATE', 'NECKTIE', 'ربطة عنق', 'original', '83', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (71, 'JOUET', 'TOY', 'لعبة', 'original', '85', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (72, 'SAC', 'BAG', 'حقيبة', 'original', '86', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (73, 'ACCESSOIRES CHEVEUX', 'HAIR ACCESSORIES', 'مستلزمات الشعر', 'original', '87', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (74, 'BRACELET', 'ARM GARTER', 'سوار', 'original', '88', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (75, 'CHAUSSETTES', 'SOCKS', 'جوارب', 'original', '91', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (76, 'BOUCLE D''OREILLES', 'EAR TAG', 'أقراط', 'original', '93', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (77, 'COLLANT', 'TIGHT', 'جوارب طويلة', 'original', '94', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (78, 'BIJOUX', 'JEWELLERY', 'مجوهرات', 'original', '95', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (79, 'bavoir', 'bib', 'مريلة', 'baby', 'BV', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (80, 'edredon', 'plaid', 'محشو بالريش لحاف', 'baby', 'CO', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (81, 'couverture', 'blanket', 'بطانية', 'baby', 'CO', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (82, 'drap housse', 'fitted sheet', 'الغطاء ستار', 'baby', 'DH', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (83, 'housse de couette', 'night set', 'اللحاف غطاء', 'baby', 'HC', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (84, 'housse de matelas à langer', 'changing mat', 'غطاء سرير متغير', 'baby', 'HO', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (85, 'mobile', 'musical mobile', 'متحرك', 'baby', 'MO', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (86, 'nid d''ange', 'carry nest', 'الملاك عش', 'baby', 'NA', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (87, 'hochet', 'rattle', 'الأطفال خشخيشة', 'baby', 'PE', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (88, 'doudou', 'plush toy', 'دودو', 'baby', 'PE', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (89, 'peluche', 'plush toy', 'من الوبر نسيج', 'baby', 'PE', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (90, 'set de bain', 'bath set', 'الحمام مجموعة', 'baby', 'SB', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (91, 'sac à langer', 'mamabag', 'متغير كيس', 'baby', 'SL', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (92, 'tapis d''éveil', 'playmat', 'سجاد للاطفال', 'baby', 'TA', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (93, 'tour de lit', 'crib bumper', 'قصيرة ستارة', 'baby', 'TL', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (94, 'turbulette', 'sleeping bag', 'النوم كيس', 'baby', 'TU', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (95, 'LUNETTES DE SOLEIL', 'SUNGLASSES', 'نظارات شمسية', 'original', '', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (96, 'boulier spirale', 'stroller toy', 'دوامة المعداد', 'baby', '', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (97, 'boite à musique', 'musical toy', 'مجموعة أجراس', 'baby', '', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (98, 'livre d''activités', 'activities book', 'للانشطة كتاب', 'baby', '', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (99, 'kit naissance', 'new born kit', 'الولادة طقم', 'baby', '', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (100, 'GUETRE', 'GAITER', 'طماق', 'original', '', NULL);
INSERT INTO "orchestra_product_family" ("id", "french", "english", "arabic", "type", "code", "team") VALUES (101, 'SAROUEL', 'SAROUAL', ' سروال', 'original', '', NULL);

INSERT INTO "orchestra_care" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (1, 'Lavage à --°C', 'Wash in --°C', 'Lavado a --°C', 'Lavado a --ºC', 'Waschen mit --°C', '温水机洗', 'X يغسل بدرجة', 'Стирка при - °C', '');
INSERT INTO "orchestra_care" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (2, 'Lavage interdit', 'No wash', 'No lavar', 'Lavagem proibida', 'Nicht waschen', '不可水洗', 'لا يغسل', 'Стирка запрещенна', NULL);
INSERT INTO "orchestra_care" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (3, 'Lavage à froid', 'Cold wash', 'Lavado en frio', 'Lavar a frio', 'Kalt waschen', '冷水机洗', 'غسيل بارد', 'Стирка в холодной воде', NULL);
INSERT INTO "orchestra_care" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (4, 'Lavage à la main', 'Hand wash', 'Lavado a mano', 'Lavar a mão', 'Handwäsche', '手洗', 'غسيل يدوي', 'Ручная стирка', NULL);
INSERT INTO "orchestra_care" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (5, 'Laver et repasser à l’envers', 'Wash and iron inside out', 'Lavar y planchar al reves', 'Virar do avesso ante de lavar – Passar do avesso', 'Von links waschen und bügeln', '反底洗熨', 'مقلوبا يكوى مقلوبا يغسل', 'СТИРАТЬ С ИЗНАНОЧНОЙ СТОРОНЫ ГЛАДИТЬ ТОЛЬКО С ИЗНАНОЧНОЙ СТОРОНЫ', NULL);
INSERT INTO "orchestra_care" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (6, 'Cycle de lavage doux', 'Gentle cycle wash', 'Lavado para ropa delicada', 'para roupa delicada', 'Schonwäsche', '轻柔转洗', 'خفيف غسيل بدوران', 'Цикл специалной стирки', NULL);
INSERT INTO "orchestra_care" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (7, 'Chlore interdit', 'No Chlorine', 'No clorar', 'Cloro interdito', 'Nicht chloren', '不可氯漂', 'بدون كلور', 'Не использовать хлор', NULL);
INSERT INTO "orchestra_care" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (8, 'Repassage doux', 'Soft ironing', 'Planchar a temperatura baja', 'Passar a ferro moderado', 'Warm bügeln', '低温熨烫', 'كي بحرارة خفيفة', 'ГЛАЖКА ПРОХЛАДНЫМ УТЮГОМ', NULL);
INSERT INTO "orchestra_care" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (9, 'Repassage moyen', 'Medium ironing', 'Planchar a temperatura media', 'Passar a ferro medio', 'Mittelwarm bügeln', '中温熨烫', 'كي بحرارة متوسطة', 'ГЛАЖКА ТЕПЛЫМ УТЮГОМ', NULL);
INSERT INTO "orchestra_care" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (10, 'Repassage chaud', 'Warm ironing', 'Planchar a temperatura caliente', 'Passar a ferro forte', 'Heiss bügeln', '高温熨烫', 'كي بحرارة عالية', 'ГЛАЖКА ГОРЯЧИМ УТЮГОМ', NULL);
INSERT INTO "orchestra_care" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (11, 'Repassage autorisé', 'Ironing', 'planchar', 'Passar a ferro', 'Bügeln erlaubt', '温熨烫', 'كوي', 'Гладить', NULL);
INSERT INTO "orchestra_care" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (12, 'Repassage interdit', 'No iron', 'Sin planchar', 'Proibido passar a ferro', 'Nicht bügeln', '不可熨烫', 'بدون كوي', 'Не гладить', NULL);
INSERT INTO "orchestra_care" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (13, 'Pas de nettoyage à sec', 'No dry cleaning', 'No limpiar en seco', 'Nao limpar a seco', 'Keine chemische Reinigung', '不可干洗', 'لا للتنظيف الجاف', 'Химическая чистка запрещена', NULL);
INSERT INTO "orchestra_care" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (14, 'Séchage à plat', 'Dry flat', 'Secar en superficie plana', 'Secar em superficie plana', 'Liegend Trocknen', '平放晾干', 'يترك ليجف تلقائيا', 'СУШИТЬ НА ПЛОСКОЙ ПОВЕРХНОСТИ', NULL);
INSERT INTO "orchestra_care" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (15, 'Sèche linge autorisé', 'Dry Tumbler', 'Secadora', 'Secadora', 'Wäschetrockner', '可滚筒烘干', 'لا للمجفف', 'Сушка в стиральной машине', NULL);
INSERT INTO "orchestra_care" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (16, 'Sèche linge interdit', 'No Dry Tumbler', 'No usar secadora', 'Ao usar secadora', 'Kein Trockner', '不可滚筒烘干', 'لا مجفف', 'Машинная сушка запрещена', NULL);
INSERT INTO "orchestra_care" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (17, 'Laver Separement', 'Wash Separately', 'Lavar por Separado', 'Lavar Separadamente', 'Separat Waschen', '分开洗', 'يغسل على انفراد', 'Стирать отдельно', NULL);
INSERT INTO "orchestra_care" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (18, 'Nettoyage a sec autorise', 'Dry cleaning allowed', 'Limpieza en seco autorizado', 'Lavagem a seco autorisado', 'Nur chemisch reinigen', '可以干洗', 'الجاف بالتنظيف مسموح', 'ВОЗМОЖНА ХИМИЧЕСКАЯ ЧИСТКА', NULL);
INSERT INTO "orchestra_care" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (19, 'Coloris foncés à laver séparément', 'Wash dark colors separately', 'Lavar los colores oscuros por separado', 'Lavar as cores escuras separadas', 'Dunkle Farben getrennt waschen ', '个别洗', 'لوحدها تغسل القاتمة الالوان', 'Стирать с темными вещами', NULL);
INSERT INTO "orchestra_care" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (20, 'Lavage sur envers en filet', 'Wash inside out in a mesh bag', 'Lavar al reves en una bolsa de malla', 'Lavar as avesas em saco', ' Auf links und im Netz waschen ', '洗衣网内水洗', 'يغسل في شبكة', 'Стирать в сетке ', NULL);
INSERT INTO "orchestra_care" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (21, 'Séchage en filet', 'Dry in a mesh bag', 'Secar en una bolsa de malla', 'Sacagerm en saco', 'Im Netz trocknen ', '织品置于洗衣网内烘干', 'يجفف في شبكة', 'Сушить в сетке', NULL);
INSERT INTO "orchestra_care" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (22, 'Repasser à l’envers', 'Iron on reverse side', 'Planchar al interior', 'Ferro no verso', 'Bügeleisen auf der Rückseite', '反面熨烫', 'الكي على المقلوب', 'железа на обратном', NULL);
INSERT INTO "orchestra_care" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (23, 'Lavage à 30 °C', 'Wash in 30 °C', 'Lavado a 30 °C', 'Lavado a 30 ºC', 'Waschen mit 30 °C', '温水机洗', '30 يغسل بدرجة', 'Стирка при 30 °C', '');
INSERT INTO "orchestra_care" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (24, 'Laver avec des coloris similaires', 'Wash with similar colors', 'Lavar con colores similares', 'Lave com cores semelhantes', 'Mit gleichartigen kolorien waschen', '相近色水洗', 'مماثلة ألوان مع تغسل ', 'Мыть с похожими цветами', NULL);
INSERT INTO "orchestra_care" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (25, 'Séchage à plat sans essorage préalable ', 'Drying flat without preliminary wringing', 'Secar de plano sin haberlo contrifugado', 'Secando com prato sem preliminar torcer', 'Flach trocknen, ohne Wringen oder Schleudern', '完全平铺情况下烘干', 'مسبق تجفيف بدون مسطح تجفيف', 'сушить на плоской поверхности без отжима', NULL);

INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (1, 'Machine wash 30°C', '/images/care_label/washing_s12_1a.jpg', 'Washing', 1, NULL);
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (2, 'Machine wash 40°C', '/images/care_label/washing_s12_1b.jpg', 'Washing', 1, NULL);
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (3, 'Machine wash 60°C', '/images/care_label/washing_s12_1c.jpg', 'Washing', 1, NULL);
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (4, 'Machine wash 95°C', '/images/care_label/washing_s12_1d.jpg', 'Washing', 1, NULL);
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (5, 'Hand wash', '/images/care_label/washing_s12_2.jpg', 'Washing', 1, NULL);
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (6, 'Machine wash 30°C, Gentle action wash', '/images/care_label/washing_s12_3a.jpg', 'Washing', 1, NULL);
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (7, 'Machine wash 40°C, Gentle action wash', '/images/care_label/washing_s12_3b.jpg', 'Washing', 1, NULL);
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (8, 'Machine wash 60°C, Gentle action wash', '/images/care_label/washing_s12_3c.jpg', 'Washing', 1, NULL);
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (9, 'Machine wash 95°C, Gentle action wash', '/images/care_label/washing_s12_3d.jpg', 'Washing', 1, NULL);
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (10, 'Do not machine wash', '/images/care_label/washing_s12_4.jpg', 'Washing', 1, NULL);
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (11, 'Bleachable', '/images/care_label/bleeding_s12_1.jpg', 'Bleeding', 2, NULL);
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (12, 'Do not bleach', '/images/care_label/bleeding_s12_2a.jpg', 'Bleeding', 2, NULL);
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (13, 'Tumble dry medium', '/images/care_label/various_s12_1.jpg', 'Various', 3, NULL);
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (14, 'Tumble dry light', '/images/care_label/various_s12_2.jpg', 'Various', 3, NULL);
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (15, 'Do not machine dry', '/images/care_label/various_s12_3.jpg', 'Various', 3, NULL);
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (16, 'Hot iron 200°C', '/images/care_label/ironing_s12_1.jpg', 'Ironing', 4, NULL);
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (17, 'Warm iron 150°C', '/images/care_label/ironing_s12_2.jpg', 'Ironing', 4, NULL);
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (18, 'Cool iron 110°C', '/images/care_label/ironing_s12_3.jpg', 'Ironing', 4, NULL);
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (19, 'Do not iron', '/images/care_label/ironing_s12_4.jpg', 'Ironing', 4, NULL);
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (20, 'Dry clean (P/F)', '/images/care_label/accessories_s12_1.jpg', 'Accessories', 5, NULL);
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (21, 'Do not dry clean', '/images/care_label/accessories_s12_2.jpg', 'Accessories', 5, NULL);
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (22, 'Dry clean, gentle action wash (P/F)', '/images/care_label/accessories_s12_3.jpg', 'Accessories', 5, NULL);
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (23, NULL, '/images/care_label/orchestra/wash_01.gif', 'wash', 1, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (24, NULL, '/images/care_label/orchestra/wash_02.gif', 'wash', 1, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (25, NULL, '/images/care_label/orchestra/wash_03.gif', 'wash', 1, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (26, NULL, '/images/care_label/orchestra/wash_04.gif', 'wash', 1, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (27, NULL, '/images/care_label/orchestra/wash_05.gif', 'wash', 1, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (28, NULL, '/images/care_label/orchestra/wash_06.gif', 'wash', 1, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (29, NULL, '/images/care_label/orchestra/wash_07.gif', 'wash', 1, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (30, NULL, '/images/care_label/orchestra/wash_08.gif', 'wash', 1, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (31, NULL, '/images/care_label/orchestra/wash_09.gif', 'wash', 1, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (32, NULL, '/images/care_label/orchestra/wash_10.gif', 'wash', 1, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (33, NULL, '/images/care_label/orchestra/wash_11.gif', 'wash', 1, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (34, NULL, '/images/care_label/orchestra/wash_12.gif', 'wash', 1, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (35, NULL, '/images/care_label/orchestra/wash_13.gif', 'wash', 1, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (36, NULL, '/images/care_label/orchestra/wash_14.gif', 'wash', 1, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (37, NULL, '/images/care_label/orchestra/wash_15.gif', 'wash', 1, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (38, NULL, '/images/care_label/orchestra/wash_16.gif', 'wash', 1, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (39, NULL, '/images/care_label/orchestra/wash_17.gif', 'wash', 1, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (40, NULL, '/images/care_label/orchestra/wash_18.gif', 'wash', 1, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (41, NULL, '/images/care_label/orchestra/wash_19.gif', 'wash', 1, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (42, NULL, '/images/care_label/orchestra/wash_20.gif', 'wash', 1, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (43, NULL, '/images/care_label/orchestra/wash_21.gif', 'wash', 1, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (44, NULL, '/images/care_label/orchestra/wash_22.gif', 'wash', 1, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (45, NULL, '/images/care_label/orchestra/wash_23.gif', 'wash', 1, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (46, NULL, '/images/care_label/orchestra/wash_24.gif', 'wash', 1, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (47, NULL, '/images/care_label/orchestra/wash_25.gif', 'wash', 1, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (48, NULL, '/images/care_label/orchestra/bleach_01.gif', 'bleach', 2, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (49, NULL, '/images/care_label/orchestra/bleach_02.gif', 'bleach', 2, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (50, NULL, '/images/care_label/orchestra/bleach_03.gif', 'bleach', 2, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (51, NULL, '/images/care_label/orchestra/bleach_04.gif', 'bleach', 2, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (52, NULL, '/images/care_label/orchestra/dry_01.gif', 'dry', 3, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (53, NULL, '/images/care_label/orchestra/dry_02.gif', 'dry', 3, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (54, NULL, '/images/care_label/orchestra/dry_03.gif', 'dry', 3, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (55, NULL, '/images/care_label/orchestra/dry_04.gif', 'dry', 3, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (56, NULL, '/images/care_label/orchestra/dry_05.gif', 'dry', 3, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (57, NULL, '/images/care_label/orchestra/dry_06.gif', 'dry', 3, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (58, NULL, '/images/care_label/orchestra/dry_07.gif', 'dry', 3, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (59, NULL, '/images/care_label/orchestra/dry_08.gif', 'dry', 3, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (60, NULL, '/images/care_label/orchestra/dry_09.gif', 'dry', 3, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (61, NULL, '/images/care_label/orchestra/dry_10.gif', 'dry', 3, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (62, NULL, '/images/care_label/orchestra/dry_11.gif', 'dry', 3, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (63, NULL, '/images/care_label/orchestra/dry_12.gif', 'dry', 3, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (64, NULL, '/images/care_label/orchestra/dry_13.gif', 'dry', 3, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (65, NULL, '/images/care_label/orchestra/dry_14.gif', 'dry', 3, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (66, NULL, '/images/care_label/orchestra/dry_15.gif', 'dry', 3, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (67, NULL, '/images/care_label/orchestra/iron_01.gif', 'iron', 4, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (68, NULL, '/images/care_label/orchestra/iron_02.gif', 'iron', 4, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (69, NULL, '/images/care_label/orchestra/iron_03.gif', 'iron', 4, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (70, NULL, '/images/care_label/orchestra/iron_04.gif', 'iron', 4, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (71, NULL, '/images/care_label/orchestra/iron_05.gif', 'iron', 4, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (72, NULL, '/images/care_label/orchestra/clean_01.gif', 'clean', 5, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (73, NULL, '/images/care_label/orchestra/clean_02.gif', 'clean', 5, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (74, NULL, '/images/care_label/orchestra/clean_03.gif', 'clean', 5, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (75, NULL, '/images/care_label/orchestra/clean_04.gif', 'clean', 5, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (76, NULL, '/images/care_label/orchestra/clean_05.gif', 'clean', 5, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (77, NULL, '/images/care_label/orchestra/clean_06.gif', 'clean', 5, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (78, NULL, '/images/care_label/orchestra/clean_07.gif', 'clean', 5, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (79, NULL, '/images/care_label/orchestra/clean_08.gif', 'clean', 5, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (80, NULL, '/images/care_label/orchestra/clean_09.gif', 'clean', 5, 'SH');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (81, NULL, '/images/care_label/hk/washing_01.gif', 'washing', 1, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (82, NULL, '/images/care_label/hk/washing_02.gif', 'washing', 1, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (83, NULL, '/images/care_label/hk/washing_03.gif', 'washing', 1, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (84, NULL, '/images/care_label/hk/washing_04.gif', 'washing', 1, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (85, NULL, '/images/care_label/hk/washing_05.gif', 'washing', 1, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (86, NULL, '/images/care_label/hk/washing_06.gif', 'washing', 1, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (87, NULL, '/images/care_label/hk/washing_07.gif', 'washing', 1, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (88, NULL, '/images/care_label/hk/washing_08.gif', 'washing', 1, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (89, NULL, '/images/care_label/hk/washing_09.gif', 'washing', 1, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (90, NULL, '/images/care_label/hk/washing_10.gif', 'washing', 1, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (91, NULL, '/images/care_label/hk/washing_11.gif', 'washing', 1, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (92, NULL, '/images/care_label/hk/washing_12.gif', 'washing', 1, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (93, NULL, '/images/care_label/hk/washing_13.gif', 'washing', 1, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (94, NULL, '/images/care_label/hk/washing_14.gif', 'washing', 1, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (95, NULL, '/images/care_label/hk/washing_15.gif', 'washing', 1, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (96, NULL, '/images/care_label/hk/bleach_01.gif', 'bleaching', 2, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (97, NULL, '/images/care_label/hk/bleach_02.gif', 'bleaching', 2, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (98, NULL, '/images/care_label/hk/bleach_03.gif', 'bleaching', 2, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (99, NULL, '/images/care_label/hk/drying_01.gif', 'drying', 3, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (100, NULL, '/images/care_label/hk/drying_02.gif', 'drying', 3, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (101, NULL, '/images/care_label/hk/drying_03.gif', 'drying', 3, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (102, NULL, '/images/care_label/hk/drying_04.gif', 'drying', 3, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (103, NULL, '/images/care_label/hk/ironing_01.gif', 'ironing', 4, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (104, NULL, '/images/care_label/hk/ironing_02.gif', 'ironing', 4, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (105, NULL, '/images/care_label/hk/ironing_03.gif', 'ironing', 4, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (106, NULL, '/images/care_label/hk/ironing_04.gif', 'ironing', 4, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (107, NULL, '/images/care_label/hk/ironing_05.gif', 'ironing', 4, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (108, NULL, '/images/care_label/hk/cleaning_01.gif', 'cleaning', 5, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (109, NULL, '/images/care_label/hk/cleaning_02.gif', 'cleaning', 5, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (110, NULL, '/images/care_label/hk/cleaning_03.gif', 'cleaning', 5, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (111, NULL, '/images/care_label/hk/cleaning_04.gif', 'cleaning', 5, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (112, NULL, '/images/care_label/hk/cleaning_05.gif', 'cleaning', 5, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (113, NULL, '/images/care_label/hk/cleaning_06.gif', 'cleaning', 5, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (114, NULL, '/images/care_label/hk/cleaning_07.gif', 'cleaning', 5, 'HK');
INSERT INTO "orchestra_care_img" ("id", "name", "path", "type", "rank", "team") VALUES (115, NULL, '/images/care_label/hk/cleaning_08.gif', 'cleaning', 5, 'HK');

INSERT INTO "orchestra_origin" ("id", "name", "french", "english", "spanish", "arabic", "chinese", "rank", "team") VALUES (1, 'Spain', 'Pays d''Origine: Espagne', 'Made in Spain', 'Hecho en España', 'بلد المنشأ : اسبانيا', '原产地：西班牙', 2, NULL);
INSERT INTO "orchestra_origin" ("id", "name", "french", "english", "spanish", "arabic", "chinese", "rank", "team") VALUES (2, 'Greece', 'Pays d''Origine: Grèce', 'Made in Greece', 'Hecho en Grecia', 'بلد المنشأ : اليونان', '原产地：希腊', 2, NULL);
INSERT INTO "orchestra_origin" ("id", "name", "french", "english", "spanish", "arabic", "chinese", "rank", "team") VALUES (3, 'Hong Kong', 'Pays d''Origine: Hong Kong', 'Made in Hong Kong', 'Hecho en Hong Kong', 'بلد المنشأ : هونغ كونغ', '原产地：香港', 2, NULL);
INSERT INTO "orchestra_origin" ("id", "name", "french", "english", "spanish", "arabic", "chinese", "rank", "team") VALUES (4, 'Marocco', 'Pays d''Origine: Maroc', 'Made in Marocco', 'Hecho en Marruecos', 'بلد المنشأ : المغرب', '原产地：摩洛哥', 2, NULL);
INSERT INTO "orchestra_origin" ("id", "name", "french", "english", "spanish", "arabic", "chinese", "rank", "team") VALUES (5, 'Tunisia', 'Pays d''Origine: Tunisie', 'Made in Tunisia', 'Hecho en Tùnez', 'بلد المنشأ : تونس', '原产地：突尼斯', 2, NULL);
INSERT INTO "orchestra_origin" ("id", "name", "french", "english", "spanish", "arabic", "chinese", "rank", "team") VALUES (6, 'Bangladesh', 'Pays d''Origine: Bengladesh', 'Made in Bangladesh', 'Hecho en Bangladesh', 'بلد المنشأ : بنغلاديش', '原产地：孟加拉', 2, NULL);
INSERT INTO "orchestra_origin" ("id", "name", "french", "english", "spanish", "arabic", "chinese", "rank", "team") VALUES (7, 'China', 'Pays d''Origine: Chine', 'Made in China', 'Hecho en China', 'بلد المنشأ : الصين', '原产地：中国', 2, NULL);
INSERT INTO "orchestra_origin" ("id", "name", "french", "english", "spanish", "arabic", "chinese", "rank", "team") VALUES (8, 'France', 'Pays d''Origine: France', 'Made in France', 'Hecho en Francia', 'بلد المنشأ : فرنسا', '原产地：法国', 2, NULL);
INSERT INTO "orchestra_origin" ("id", "name", "french", "english", "spanish", "arabic", "chinese", "rank", "team") VALUES (9, 'Mauritius Island', 'Pays d''Origine: Ile Maurice', 'Made in Mauritius Island', 'Hecho en Mauricio', 'بلد المنشأ : موريشيوس', '原产地：毛里求斯', 2, NULL);
INSERT INTO "orchestra_origin" ("id", "name", "french", "english", "spanish", "arabic", "chinese", "rank", "team") VALUES (10, 'India', 'Pays d''Origine: Inde', 'Made in India', 'Hecho en India', 'بلد المنشأ : الهند', '原产地：印度', 2, NULL);
INSERT INTO "orchestra_origin" ("id", "name", "french", "english", "spanish", "arabic", "chinese", "rank", "team") VALUES (11, 'Italia', 'Pays d''Origine: Italie', 'Made in Italia', 'Hecho en Italia', 'بلد المنشأ : ايطاليا', '原产地：意大利', 2, NULL);
INSERT INTO "orchestra_origin" ("id", "name", "french", "english", "spanish", "arabic", "chinese", "rank", "team") VALUES (12, 'Madagascar', 'Pays d''Origine: Madagascar', 'Made in Madagascar', 'Hecho en Madagascar', 'بلد المنشأ : مدغشقر', '原产地：马达加斯加', 2, NULL);
INSERT INTO "orchestra_origin" ("id", "name", "french", "english", "spanish", "arabic", "chinese", "rank", "team") VALUES (13, 'Philippines', 'Pays d''Origine: Philippines', 'Made in Philippines', 'Hecho en Filipinas', 'بلد المنشأ : الفلبين', '原产地：菲律宾', 2, NULL);
INSERT INTO "orchestra_origin" ("id", "name", "french", "english", "spanish", "arabic", "chinese", "rank", "team") VALUES (14, 'Portugal', 'Pays d''Origine: Portugal', 'Made in Portugal', 'Hecho en Portugal', 'بلد المنشأ : البرتغال', '原产地：葡萄牙', 2, NULL);
INSERT INTO "orchestra_origin" ("id", "name", "french", "english", "spanish", "arabic", "chinese", "rank", "team") VALUES (15, 'Syria', 'Pays d''Origine: Syrie', 'Made in Syria', 'Hecho en Siria', 'بلد المنشأ : سوريا', '原产地：叙利亚', 2, NULL);
INSERT INTO "orchestra_origin" ("id", "name", "french", "english", "spanish", "arabic", "chinese", "rank", "team") VALUES (16, 'Turkey', 'Pays d''Origine: Turquie', 'Made in Turkey', 'Hecho en Turquia', 'بلد المنشأ : تركيا', '原产地：土耳其', 2, NULL);
INSERT INTO "orchestra_origin" ("id", "name", "french", "english", "spanish", "arabic", "chinese", "rank", "team") VALUES (17, 'Taiwan', 'Pays d''Origine: Taïwan', 'Made in Taiwan', 'Hecho en Taïwan', 'بلد المنشأ : تايوان', '原产地：台湾', 2, NULL);
INSERT INTO "orchestra_origin" ("id", "name", "french", "english", "spanish", "arabic", "chinese", "rank", "team") VALUES (18, 'Pakistan', 'Pays d''Origine: Pakistan', 'Made in Pakistan', 'Hecho en Pakistan', 'بلد المنشأ : باكستان', '原产地：巴基斯坦', 2, NULL);
INSERT INTO "orchestra_origin" ("id", "name", "french", "english", "spanish", "arabic", "chinese", "rank", "team") VALUES (19, 'Vietnam', 'Pays d''Origine: Vietnam', 'Made in Vietnam', 'Hecho en Vietnam', 'بلد المنشأ : فيتنام', '原产地：越南', 2, NULL);
INSERT INTO "orchestra_origin" ("id", "name", "french", "english", "spanish", "arabic", "chinese", "rank", "team") VALUES (20, 'Cambodia', '', 'Made in Cambodia', 'Hecho en Camboya', 'بلد المنشأ :كمبوديا', '原产地：柬埔寨', 1, NULL);

INSERT INTO "orchestra_item" ("id", "name", "info1", "team") VALUES (1, 'original', NULL, NULL);
INSERT INTO "orchestra_item" ("id", "name", "info1", "team") VALUES (2, 'trousers ', '腰围:', 'HK');
INSERT INTO "orchestra_item" ("id", "name", "info1", "team") VALUES (3, 'jacket ', '胸围:', 'HK');

INSERT INTO "orchestra_fabric" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (1, 'Tissu', 'Shell', 'Tecido', 'Stoff', '', '面料', 'قذيفة النسيج', 'ткань оболочки', NULL);
INSERT INTO "orchestra_fabric" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (2, 'Doublure', 'Lining', 'forro', 'Innenfutter', NULL, '内里', 'البطانة', 'подкладка', NULL);
INSERT INTO "orchestra_fabric" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (3, 'Ouatinage', 'Padding', 'acolchada', 'acolchoado', 'wattierung', '填充料', 'بطانة', NULL, NULL);

INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (1, 'Acétate', 'Acetate', 'Acetato', 'Acetato', 'Acetat', '醋纤', 'استأت', 'Ацетат', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (2, 'Acrylique', 'Acrylic', 'Acrilico', 'Acrilico', 'Acryl', '腈纶', 'اكريليك', 'Акрил', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (3, 'Autre fibres', 'Others fibers', 'Otras fibras', 'Outras fibras', 'Andere Fasern', '其它纤维', 'ألياف أخرى', 'Другие волокна', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (4, 'Cachemire', 'Cashmere', 'Cachemir', 'Cachemira', 'Kaschmir', '羊绒', 'قماش كشمير', 'Кашемир', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (5, 'Chanvre', 'Hemp', 'Cáñamo', 'Cânhamo', 'Hanf', '大麻纤维', 'القنب', 'Конопля', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (6, 'Coco', 'Coconut', 'Coco', 'côco', 'Kokosnuss', '椰子纤维', 'التيل', 'Кокос', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (7, 'Coton', 'Cotton', 'Algodón', 'Algodão', 'Baumwolle', '棉', 'القطن', 'Хлопок', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (8, 'Cuir', 'Leather', 'Cuero', 'Couro', 'Leder', '皮革', 'الجلد', 'Кожа', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (9, 'Doublure', 'lining', 'forro', 'forro', 'Innenfutter', '内里', 'البطانة', 'подкладка ', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (10, 'Elasthanne', 'Elastane', 'Elastano', 'Elastano', 'Elastan', '氨纶', 'الالستان/', 'Эластан', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (11, 'Fourrure', 'Fur', 'Piel', 'Pele', 'Pelz', '毛皮', 'الفراء', 'Мех', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (12, 'Jute', 'Jute', 'Yute', 'Juta', 'Jute', '黃麻', 'جوت', 'Джут', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (13, 'Laine', 'Wool', 'Lana', 'Lã', 'Wolle', '羊毛', 'الصوف', 'Шерсть', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (14, 'Lin', 'Linen', 'Lino', 'Linho', 'Leinen', '亚麻', 'قماش الكتان', 'Лен', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (15, 'Métal / Lurex', 'Metal / Lurex', 'Metal / Lúrex', 'Metal / Lurex', 'Metall', '金属线', 'معدني', 'Металл / Люрекс', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (16, 'Ouatinage', 'Padding', 'acolchada', 'acolchoado', 'wattierung', '填充料', 'بطانة', 'подбитый ватином ', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (17, 'Paille', 'Straw', 'Paja', 'Palha', 'Stroh', '稻草', 'القش', 'Солома', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (18, 'Papier', 'Paper', 'Papel', 'Papel', 'Papier', '纸', 'ورق', 'Бумага', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (19, 'Polyamide', 'Polyamide', 'Poliamida', 'Poliamida', 'Polyamid', '锦纶', 'نايلون', 'Полиамид', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (20, 'PVC', 'Polyvinyl chloride', 'Cloruro de Polivinilo', 'Policloreto de vinila', 'Polyvinylchlorid', '聚氯乙烯', 'بولي فينيل كلوريد', 'Пластмасса', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (21, 'Polyester', 'Polyester', 'poliéster', 'polièster', 'Polyester', '涤纶', 'البولستر', 'Полиэстер', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (22, 'Polyuréthane', 'Polyurethane', 'Poliuretano', 'Poliuretana', 'Polyurethan', '聚亚安酯', 'مصنعة بلاستيكية مادة', 'Полиуретан', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (23, 'Soie', 'Silk', 'Seda', 'Seda', 'Seide', '蚕丝', 'الحرير', 'Шелк', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (24, 'Synthétique', 'Synthetic', 'sintético', 'sintético', 'synthetisch', '合成', 'إصطِناعي ،تركيبي ;تركيبي', 'синтетический', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (25, 'Viscose', 'Viscose', 'Viscosa', 'Viscose', 'Viskose', '粘胶', 'فسكوس', 'Вискоза', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (26, 'Angora', 'Angora', 'Angora', 'Angora', 'Angora', '安哥拉兔毛', 'انغورا', 'Ангорский', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (27, 'Nylon', 'Nylon', 'Nylon', 'Nylon', 'Nylon', '尼龙', 'نايلون', 'Нейлон', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (28, 'Résine époxy', 'Epoxy', 'Resina epoxy', 'Epóxi', 'Epoxy', '环氧树脂', 'الايبوكسي', 'эпоксидная смола', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (29, 'Polyrésine', 'Polyresin', 'Poliresina', 'Polyresin', 'Polyresin', '树脂', 'بوليريسين', 'полистоуна', NULL);
INSERT INTO "orchestra_composition" ("id", "french", "english", "spanish", "portugese", "german", "chinese", "arabic", "russian", "team") VALUES (30, 'Plastique', 'Plastic', 'Plástico', 'Plástico', 'Kunstoff', '塑料', 'البلاستيك', 'пластик', NULL);